name: pi

services:
  backend:
    build: 
      context: server
      target: dev
    volumes:
      - ./server:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    entrypoint: npm run start

volumes:
  backend_node_modules: