name: pi

services:
  backend:
    build: 
      context: server
      target: dev
    container_name: backend
    volumes:
      - ./server:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    ports:
      - "${SERVERPORT}:${SERVERPORT}"
    environment:
      - SERVERPORT=${SERVERPORT}
    entrypoint: npm run start

  frontend:
    build: 
      context: web
      target: dev
    container_name: frontend
    volumes:
      - ./web:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    ports:
      - "${WEBPORT}:${WEBPORT}"
    environment:
      - WEBPORT=${WEBPORT}
    entrypoint: npm run dev

volumes:
  backend_node_modules:
  frontend_node_modules: