name: pi

services:
  backend:
    build: 
      context: server
      target: dev
    volumes:
      - ./server:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    ports:
      - "${SERVERPORT}:${SERVERPORT}"
    environment:
      - SERVERPORT=${SERVERPORT}
    entrypoint: npm run start

volumes:
  backend_node_modules: